# Dockerfile for logtensec
#
# Lack of a file extension might be the single worst engineering decision in
# the whole storied existence of Docker.

FROM alpine:latest
COPY logtensec /
ENTRYPOINT ["/logtensec"]
